/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

let value: ListTemplatesResponse = {
  items: [
    {
      id: "<id>",
      name: "order_confirmation",
      language: "en",
      body: "Hi {{"{{"}}1}}, your order {{"{{"}}2}} has shipped.",
      category: "UTILITY",
    },
  ],
};