/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createSender } from "../funcs/createSender.js";
import { createTemplate } from "../funcs/createTemplate.js";
import { deleteSender } from "../funcs/deleteSender.js";
import { deleteTemplate } from "../funcs/deleteTemplate.js";
import { getContact } from "../funcs/getContact.js";
import { getContactByPhone } from "../funcs/getContactByPhone.js";
import { getMessage } from "../funcs/getMessage.js";
import { getSender } from "../funcs/getSender.js";
import { getTemplate } from "../funcs/getTemplate.js";
import { introspectPhone } from "../funcs/introspectPhone.js";
import { listContacts } from "../funcs/listContacts.js";
import { listMessages } from "../funcs/listMessages.js";
import { listSenders } from "../funcs/listSenders.js";
import { listTemplates } from "../funcs/listTemplates.js";
import { sendMessage } from "../funcs/sendMessage.js";
import { sendReaction } from "../funcs/sendReaction.js";
import { updateContact } from "../funcs/updateContact.js";
import { updateSender } from "../funcs/updateSender.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Zavu extends ClientSDK {
  /**
   * Send a message
   *
   * @remarks
   * Send a message to a recipient via SMS or WhatsApp.
   *
   * **Channel selection:**
   * - If `channel` is omitted and `messageType` is `text`, defaults to SMS
   * - If `messageType` is anything other than `text`, WhatsApp is used automatically
   *
   * **WhatsApp 24-hour window:**
   * - Free-form messages (non-template) require an open 24h window
   * - Window opens when the user messages you first
   * - Use template messages to initiate conversations outside the window
   */
  async sendMessage(
    request: operations.SendMessageRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(sendMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * List messages
   *
   * @remarks
   * List messages previously sent by this project.
   */
  async listMessages(
    request?: operations.ListMessagesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListMessagesResponse> {
    return unwrapAsync(listMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Get message by ID
   */
  async getMessage(
    request: operations.GetMessageRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(getMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Send reaction to message
   *
   * @remarks
   * Send an emoji reaction to an existing WhatsApp message. Reactions are only supported for WhatsApp messages.
   */
  async sendReaction(
    request: operations.SendReactionRequest,
    options?: RequestOptions,
  ): Promise<models.MessageResponse> {
    return unwrapAsync(sendReaction(
      this,
      request,
      options,
    ));
  }

  /**
   * List templates
   *
   * @remarks
   * List WhatsApp message templates for this project.
   */
  async listTemplates(
    options?: RequestOptions,
  ): Promise<operations.ListTemplatesResponse> {
    return unwrapAsync(listTemplates(
      this,
      options,
    ));
  }

  /**
   * Create template
   *
   * @remarks
   * Create a WhatsApp message template. Note: Templates must be approved by Meta before use.
   */
  async createTemplate(
    request: models.TemplateCreateRequest,
    options?: RequestOptions,
  ): Promise<models.Template> {
    return unwrapAsync(createTemplate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get template
   */
  async getTemplate(
    request: operations.GetTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.Template> {
    return unwrapAsync(getTemplate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete template
   */
  async deleteTemplate(
    request: operations.DeleteTemplateRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(deleteTemplate(
      this,
      request,
      options,
    ));
  }

  /**
   * List senders
   */
  async listSenders(
    options?: RequestOptions,
  ): Promise<operations.ListSendersResponse> {
    return unwrapAsync(listSenders(
      this,
      options,
    ));
  }

  /**
   * Create sender
   */
  async createSender(
    request: models.SenderCreateRequest,
    options?: RequestOptions,
  ): Promise<models.Sender> {
    return unwrapAsync(createSender(
      this,
      request,
      options,
    ));
  }

  /**
   * Get sender
   */
  async getSender(
    request: operations.GetSenderRequest,
    options?: RequestOptions,
  ): Promise<models.Sender> {
    return unwrapAsync(getSender(
      this,
      request,
      options,
    ));
  }

  /**
   * Update sender
   */
  async updateSender(
    request: operations.UpdateSenderRequest,
    options?: RequestOptions,
  ): Promise<models.Sender> {
    return unwrapAsync(updateSender(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete sender
   */
  async deleteSender(
    request: operations.DeleteSenderRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(deleteSender(
      this,
      request,
      options,
    ));
  }

  /**
   * List contacts
   */
  async listContacts(
    request?: operations.ListContactsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListContactsResponse> {
    return unwrapAsync(listContacts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get contact
   */
  async getContact(
    request: operations.GetContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(getContact(
      this,
      request,
      options,
    ));
  }

  /**
   * Update contact
   */
  async updateContact(
    request: operations.UpdateContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(updateContact(
      this,
      request,
      options,
    ));
  }

  /**
   * Get contact by phone number
   */
  async getContactByPhone(
    request: operations.GetContactByPhoneRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(getContactByPhone(
      this,
      request,
      options,
    ));
  }

  /**
   * Introspect phone number
   *
   * @remarks
   * Validate a phone number and check if a WhatsApp conversation window is open.
   */
  async introspectPhone(
    request: models.PhoneIntrospectionRequest,
    options?: RequestOptions,
  ): Promise<models.PhoneIntrospectionResponse> {
    return unwrapAsync(introspectPhone(
      this,
      request,
      options,
    ));
  }
}
