/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @zavu/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx sendMessage.example.ts
 */

import { SDK } from "@zavu/sdk";

const sdk = new SDK({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await sdk.sendMessage({
    zavuSender: "sender_12345",
    body: {
      to: "+56912345678",
      text: "Your verification code is 123456",
    },
  });

  console.log(result);
}

main().catch(console.error);
