/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTemplateRequest = {
  templateId: string;
};

/** @internal */
export type DeleteTemplateRequest$Outbound = {
  templateId: string;
};

/** @internal */
export const DeleteTemplateRequest$outboundSchema: z.ZodMiniType<
  DeleteTemplateRequest$Outbound,
  DeleteTemplateRequest
> = z.object({
  templateId: z.string(),
});

export function deleteTemplateRequestToJSON(
  deleteTemplateRequest: DeleteTemplateRequest,
): string {
  return JSON.stringify(
    DeleteTemplateRequest$outboundSchema.parse(deleteTemplateRequest),
  );
}
