/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteSenderRequest = {
  senderId: string;
};

/** @internal */
export type DeleteSenderRequest$Outbound = {
  senderId: string;
};

/** @internal */
export const DeleteSenderRequest$outboundSchema: z.ZodMiniType<
  DeleteSenderRequest$Outbound,
  DeleteSenderRequest
> = z.object({
  senderId: z.string(),
});

export function deleteSenderRequestToJSON(
  deleteSenderRequest: DeleteSenderRequest,
): string {
  return JSON.stringify(
    DeleteSenderRequest$outboundSchema.parse(deleteSenderRequest),
  );
}
