/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetContactByPhoneRequest = {
  /**
   * E.164 phone number.
   */
  phoneNumber: string;
};

/** @internal */
export type GetContactByPhoneRequest$Outbound = {
  phoneNumber: string;
};

/** @internal */
export const GetContactByPhoneRequest$outboundSchema: z.ZodMiniType<
  GetContactByPhoneRequest$Outbound,
  GetContactByPhoneRequest
> = z.object({
  phoneNumber: z.string(),
});

export function getContactByPhoneRequestToJSON(
  getContactByPhoneRequest: GetContactByPhoneRequest,
): string {
  return JSON.stringify(
    GetContactByPhoneRequest$outboundSchema.parse(getContactByPhoneRequest),
  );
}
