/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetContactRequest = {
  contactId: string;
};

/** @internal */
export type GetContactRequest$Outbound = {
  contactId: string;
};

/** @internal */
export const GetContactRequest$outboundSchema: z.ZodMiniType<
  GetContactRequest$Outbound,
  GetContactRequest
> = z.object({
  contactId: z.string(),
});

export function getContactRequestToJSON(
  getContactRequest: GetContactRequest,
): string {
  return JSON.stringify(
    GetContactRequest$outboundSchema.parse(getContactRequest),
  );
}
