/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetMessageRequest = {
  messageId: string;
};

/** @internal */
export type GetMessageRequest$Outbound = {
  messageId: string;
};

/** @internal */
export const GetMessageRequest$outboundSchema: z.ZodMiniType<
  GetMessageRequest$Outbound,
  GetMessageRequest
> = z.object({
  messageId: z.string(),
});

export function getMessageRequestToJSON(
  getMessageRequest: GetMessageRequest,
): string {
  return JSON.stringify(
    GetMessageRequest$outboundSchema.parse(getMessageRequest),
  );
}
