/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSenderRequest = {
  senderId: string;
};

/** @internal */
export type GetSenderRequest$Outbound = {
  senderId: string;
};

/** @internal */
export const GetSenderRequest$outboundSchema: z.ZodMiniType<
  GetSenderRequest$Outbound,
  GetSenderRequest
> = z.object({
  senderId: z.string(),
});

export function getSenderRequestToJSON(
  getSenderRequest: GetSenderRequest,
): string {
  return JSON.stringify(
    GetSenderRequest$outboundSchema.parse(getSenderRequest),
  );
}
