/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListMessagesRequest = {
  status?: models.MessageStatus | undefined;
  to?: string | undefined;
  /**
   * Delivery channel.
   */
  channel?: models.Channel | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
};

/**
 * List of messages.
 */
export type ListMessagesResponse = {
  items: Array<models.Message>;
  nextCursor?: string | null | undefined;
};

/** @internal */
export type ListMessagesRequest$Outbound = {
  status?: string | undefined;
  to?: string | undefined;
  channel?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListMessagesRequest$outboundSchema: z.ZodMiniType<
  ListMessagesRequest$Outbound,
  ListMessagesRequest
> = z.object({
  status: z.optional(models.MessageStatus$outboundSchema),
  to: z.optional(z.string()),
  channel: z.optional(models.Channel$outboundSchema),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listMessagesRequestToJSON(
  listMessagesRequest: ListMessagesRequest,
): string {
  return JSON.stringify(
    ListMessagesRequest$outboundSchema.parse(listMessagesRequest),
  );
}

/** @internal */
export const ListMessagesResponse$inboundSchema: z.ZodMiniType<
  ListMessagesResponse,
  unknown
> = z.object({
  items: z.array(models.Message$inboundSchema),
  nextCursor: z.optional(z.nullable(types.string())),
});

export function listMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessagesResponse' from JSON`,
  );
}
