/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * List of sender profiles.
 */
export type ListSendersResponse = {
  items: Array<models.Sender>;
};

/** @internal */
export const ListSendersResponse$inboundSchema: z.ZodMiniType<
  ListSendersResponse,
  unknown
> = z.object({
  items: z.array(models.Sender$inboundSchema),
});

export function listSendersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSendersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSendersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSendersResponse' from JSON`,
  );
}
