/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * List of templates.
 */
export type ListTemplatesResponse = {
  items: Array<models.Template>;
};

/** @internal */
export const ListTemplatesResponse$inboundSchema: z.ZodMiniType<
  ListTemplatesResponse,
  unknown
> = z.object({
  items: z.array(models.Template$inboundSchema),
});

export function listTemplatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTemplatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTemplatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTemplatesResponse' from JSON`,
  );
}
