/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListContactsRequest = {
  phoneNumber?: string | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
};

/**
 * List of contacts.
 */
export type ListContactsResponse = {
  items: Array<models.Contact>;
  nextCursor?: string | null | undefined;
};

/** @internal */
export type ListContactsRequest$Outbound = {
  phoneNumber?: string | undefined;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListContactsRequest$outboundSchema: z.ZodMiniType<
  ListContactsRequest$Outbound,
  ListContactsRequest
> = z.object({
  phoneNumber: z.optional(z.string()),
  limit: z._default(z.int(), 50),
  cursor: z.optional(z.string()),
});

export function listContactsRequestToJSON(
  listContactsRequest: ListContactsRequest,
): string {
  return JSON.stringify(
    ListContactsRequest$outboundSchema.parse(listContactsRequest),
  );
}

/** @internal */
export const ListContactsResponse$inboundSchema: z.ZodMiniType<
  ListContactsResponse,
  unknown
> = z.object({
  items: z.array(models.Contact$inboundSchema),
  nextCursor: z.optional(z.nullable(types.string())),
});

export function listContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContactsResponse' from JSON`,
  );
}
