/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SendReactionRequest = {
  messageId: string;
  /**
   * Optional sender profile ID. If omitted, the project's default sender will be used.
   */
  zavuSender?: string | undefined;
  body: models.ReactionRequest;
};

/** @internal */
export type SendReactionRequest$Outbound = {
  messageId: string;
  "Zavu-Sender"?: string | undefined;
  body: models.ReactionRequest$Outbound;
};

/** @internal */
export const SendReactionRequest$outboundSchema: z.ZodMiniType<
  SendReactionRequest$Outbound,
  SendReactionRequest
> = z.pipe(
  z.object({
    messageId: z.string(),
    zavuSender: z.optional(z.string()),
    body: models.ReactionRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      zavuSender: "Zavu-Sender",
    });
  }),
);

export function sendReactionRequestToJSON(
  sendReactionRequest: SendReactionRequest,
): string {
  return JSON.stringify(
    SendReactionRequest$outboundSchema.parse(sendReactionRequest),
  );
}
