/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SendMessageRequest = {
  /**
   * Optional sender profile ID. If omitted, the project's default sender will be used.
   */
  zavuSender?: string | undefined;
  body: models.MessageRequest;
};

/** @internal */
export type SendMessageRequest$Outbound = {
  "Zavu-Sender"?: string | undefined;
  body: models.MessageRequest$Outbound;
};

/** @internal */
export const SendMessageRequest$outboundSchema: z.ZodMiniType<
  SendMessageRequest$Outbound,
  SendMessageRequest
> = z.pipe(
  z.object({
    zavuSender: z.optional(z.string()),
    body: models.MessageRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      zavuSender: "Zavu-Sender",
    });
  }),
);

export function sendMessageRequestToJSON(
  sendMessageRequest: SendMessageRequest,
): string {
  return JSON.stringify(
    SendMessageRequest$outboundSchema.parse(sendMessageRequest),
  );
}
