/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateContactRequest = {
  contactId: string;
  body: models.ContactUpdateRequest;
};

/** @internal */
export type UpdateContactRequest$Outbound = {
  contactId: string;
  body: models.ContactUpdateRequest$Outbound;
};

/** @internal */
export const UpdateContactRequest$outboundSchema: z.ZodMiniType<
  UpdateContactRequest$Outbound,
  UpdateContactRequest
> = z.object({
  contactId: z.string(),
  body: models.ContactUpdateRequest$outboundSchema,
});

export function updateContactRequestToJSON(
  updateContactRequest: UpdateContactRequest,
): string {
  return JSON.stringify(
    UpdateContactRequest$outboundSchema.parse(updateContactRequest),
  );
}
