/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateSenderRequest = {
  senderId: string;
  body: models.SenderUpdateRequest;
};

/** @internal */
export type UpdateSenderRequest$Outbound = {
  senderId: string;
  body: models.SenderUpdateRequest$Outbound;
};

/** @internal */
export const UpdateSenderRequest$outboundSchema: z.ZodMiniType<
  UpdateSenderRequest$Outbound,
  UpdateSenderRequest
> = z.object({
  senderId: z.string(),
  body: models.SenderUpdateRequest$outboundSchema,
});

export function updateSenderRequestToJSON(
  updateSenderRequest: UpdateSenderRequest,
): string {
  return JSON.stringify(
    UpdateSenderRequest$outboundSchema.parse(updateSenderRequest),
  );
}
