/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Delivery channel.
 */
export const Channel = {
  Sms: "sms",
  Whatsapp: "whatsapp",
} as const;
/**
 * Delivery channel.
 */
export type Channel = OpenEnum<typeof Channel>;

/** @internal */
export const Channel$inboundSchema: z.ZodMiniType<Channel, unknown> = openEnums
  .inboundSchema(Channel);
/** @internal */
export const Channel$outboundSchema: z.ZodMiniType<string, Channel> = openEnums
  .outboundSchema(Channel);
