/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ContactUpdateRequest = {
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export type ContactUpdateRequest$Outbound = {
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const ContactUpdateRequest$outboundSchema: z.ZodMiniType<
  ContactUpdateRequest$Outbound,
  ContactUpdateRequest
> = z.object({
  metadata: z.optional(z.record(z.string(), z.string())),
});

export function contactUpdateRequestToJSON(
  contactUpdateRequest: ContactUpdateRequest,
): string {
  return JSON.stringify(
    ContactUpdateRequest$outboundSchema.parse(contactUpdateRequest),
  );
}
