/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Contact = {
  id: string;
  /**
   * E.164 phone number.
   */
  phoneNumber: string;
  countryCode?: string | undefined;
  /**
   * Whether the 24-hour WhatsApp window is currently open.
   */
  whatsappWindowOpen?: boolean | undefined;
  /**
   * When the contact last messaged via WhatsApp.
   */
  lastWhatsappMessageAt?: Date | undefined;
  metadata?: { [k: string]: string } | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const Contact$inboundSchema: z.ZodMiniType<Contact, unknown> = z.object({
  id: types.string(),
  phoneNumber: types.string(),
  countryCode: types.optional(types.string()),
  whatsappWindowOpen: types.optional(types.boolean()),
  lastWhatsappMessageAt: types.optional(types.date()),
  metadata: types.optional(z.record(z.string(), types.string())),
  createdAt: types.optional(types.date()),
  updatedAt: types.optional(types.date()),
});

export function contactFromJSON(
  jsonString: string,
): SafeParseResult<Contact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Contact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Contact' from JSON`,
  );
}
