/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Type of message. Non-text types are WhatsApp only.
 */
export const MessageType = {
  Text: "text",
  Image: "image",
  Video: "video",
  Audio: "audio",
  Document: "document",
  Sticker: "sticker",
  Location: "location",
  Contact: "contact",
  Buttons: "buttons",
  List: "list",
  Reaction: "reaction",
  Template: "template",
} as const;
/**
 * Type of message. Non-text types are WhatsApp only.
 */
export type MessageType = OpenEnum<typeof MessageType>;

/** @internal */
export const MessageType$inboundSchema: z.ZodMiniType<MessageType, unknown> =
  openEnums.inboundSchema(MessageType);
/** @internal */
export const MessageType$outboundSchema: z.ZodMiniType<string, MessageType> =
  openEnums.outboundSchema(MessageType);
