/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Channel, Channel$inboundSchema } from "./channel.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MessageContent,
  MessageContent$inboundSchema,
} from "./messagecontent.js";
import { MessageStatus, MessageStatus$inboundSchema } from "./messagestatus.js";
import { MessageType, MessageType$inboundSchema } from "./messagetype.js";

export type Message = {
  id: string;
  to: string;
  from?: string | undefined;
  senderId?: string | undefined;
  /**
   * Delivery channel.
   */
  channel: Channel;
  /**
   * Type of message. Non-text types are WhatsApp only.
   */
  messageType: MessageType;
  status: MessageStatus;
  /**
   * Text content or caption.
   */
  text?: string | undefined;
  /**
   * Content for non-text message types (WhatsApp only).
   */
  content?: MessageContent | undefined;
  /**
   * Message ID from the delivery provider.
   */
  providerMessageId?: string | undefined;
  errorCode?: string | null | undefined;
  errorMessage?: string | null | undefined;
  metadata?: { [k: string]: string } | undefined;
  createdAt: Date;
  updatedAt?: Date | undefined;
};

/** @internal */
export const Message$inboundSchema: z.ZodMiniType<Message, unknown> = z.object({
  id: types.string(),
  to: types.string(),
  from: types.optional(types.string()),
  senderId: types.optional(types.string()),
  channel: Channel$inboundSchema,
  messageType: MessageType$inboundSchema,
  status: MessageStatus$inboundSchema,
  text: types.optional(types.string()),
  content: types.optional(MessageContent$inboundSchema),
  providerMessageId: types.optional(types.string()),
  errorCode: z.optional(z.nullable(types.string())),
  errorMessage: z.optional(z.nullable(types.string())),
  metadata: types.optional(z.record(z.string(), types.string())),
  createdAt: types.date(),
  updatedAt: types.optional(types.date()),
});

export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
