/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MessageStatus = {
  Queued: "queued",
  Sending: "sending",
  Sent: "sent",
  Delivered: "delivered",
  Read: "read",
  Failed: "failed",
} as const;
export type MessageStatus = OpenEnum<typeof MessageStatus>;

/** @internal */
export const MessageStatus$inboundSchema: z.ZodMiniType<
  MessageStatus,
  unknown
> = openEnums.inboundSchema(MessageStatus);
/** @internal */
export const MessageStatus$outboundSchema: z.ZodMiniType<
  string,
  MessageStatus
> = openEnums.outboundSchema(MessageStatus);
