/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { Channel, Channel$outboundSchema } from "./channel.js";
import {
  MessageContent,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./messagecontent.js";
import { MessageType, MessageType$outboundSchema } from "./messagetype.js";

/**
 * Request body to send a message.
 */
export type MessageRequest = {
  /**
   * Recipient phone number in E.164 format.
   */
  to: string;
  /**
   * Delivery channel.
   */
  channel?: Channel | undefined;
  /**
   * Type of message. Non-text types are WhatsApp only.
   */
  messageType?: MessageType | undefined;
  /**
   * Text body for text messages or caption for media messages.
   */
  text?: string | undefined;
  /**
   * Content for non-text message types (WhatsApp only).
   */
  content?: MessageContent | undefined;
  /**
   * Optional idempotency key to avoid duplicate sends.
   */
  idempotencyKey?: string | undefined;
  /**
   * Arbitrary metadata to associate with the message.
   */
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export type MessageRequest$Outbound = {
  to: string;
  channel?: string | undefined;
  messageType?: string | undefined;
  text?: string | undefined;
  content?: MessageContent$Outbound | undefined;
  idempotencyKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
};

/** @internal */
export const MessageRequest$outboundSchema: z.ZodMiniType<
  MessageRequest$Outbound,
  MessageRequest
> = z.object({
  to: z.string(),
  channel: z.optional(Channel$outboundSchema),
  messageType: z.optional(MessageType$outboundSchema),
  text: z.optional(z.string()),
  content: z.optional(MessageContent$outboundSchema),
  idempotencyKey: z.optional(z.string()),
  metadata: z.optional(z.record(z.string(), z.string())),
});

export function messageRequestToJSON(messageRequest: MessageRequest): string {
  return JSON.stringify(MessageRequest$outboundSchema.parse(messageRequest));
}
