/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PhoneIntrospectionRequest = {
  phoneNumber: string;
};

/** @internal */
export type PhoneIntrospectionRequest$Outbound = {
  phoneNumber: string;
};

/** @internal */
export const PhoneIntrospectionRequest$outboundSchema: z.ZodMiniType<
  PhoneIntrospectionRequest$Outbound,
  PhoneIntrospectionRequest
> = z.object({
  phoneNumber: z.string(),
});

export function phoneIntrospectionRequestToJSON(
  phoneIntrospectionRequest: PhoneIntrospectionRequest,
): string {
  return JSON.stringify(
    PhoneIntrospectionRequest$outboundSchema.parse(phoneIntrospectionRequest),
  );
}
