/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PhoneIntrospectionResponse = {
  phoneNumber: string;
  countryCode: string;
  validNumber: boolean;
  /**
   * Whether a 24h WhatsApp window is open for this number.
   */
  whatsappWindowOpen?: boolean | undefined;
};

/** @internal */
export const PhoneIntrospectionResponse$inboundSchema: z.ZodMiniType<
  PhoneIntrospectionResponse,
  unknown
> = z.object({
  phoneNumber: types.string(),
  countryCode: types.string(),
  validNumber: types.boolean(),
  whatsappWindowOpen: types.optional(types.boolean()),
});

export function phoneIntrospectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<PhoneIntrospectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PhoneIntrospectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PhoneIntrospectionResponse' from JSON`,
  );
}
