/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ReactionRequest = {
  /**
   * Single emoji character to react with.
   */
  emoji: string;
};

/** @internal */
export type ReactionRequest$Outbound = {
  emoji: string;
};

/** @internal */
export const ReactionRequest$outboundSchema: z.ZodMiniType<
  ReactionRequest$Outbound,
  ReactionRequest
> = z.object({
  emoji: z.string(),
});

export function reactionRequestToJSON(
  reactionRequest: ReactionRequest,
): string {
  return JSON.stringify(ReactionRequest$outboundSchema.parse(reactionRequest));
}
