/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SenderCreateRequest = {
  name: string;
  phoneNumber: string;
  setAsDefault?: boolean | undefined;
};

/** @internal */
export type SenderCreateRequest$Outbound = {
  name: string;
  phoneNumber: string;
  setAsDefault: boolean;
};

/** @internal */
export const SenderCreateRequest$outboundSchema: z.ZodMiniType<
  SenderCreateRequest$Outbound,
  SenderCreateRequest
> = z.object({
  name: z.string(),
  phoneNumber: z.string(),
  setAsDefault: z._default(z.boolean(), false),
});

export function senderCreateRequestToJSON(
  senderCreateRequest: SenderCreateRequest,
): string {
  return JSON.stringify(
    SenderCreateRequest$outboundSchema.parse(senderCreateRequest),
  );
}
