/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SenderUpdateRequest = {
  name?: string | undefined;
  setAsDefault?: boolean | undefined;
};

/** @internal */
export type SenderUpdateRequest$Outbound = {
  name?: string | undefined;
  setAsDefault?: boolean | undefined;
};

/** @internal */
export const SenderUpdateRequest$outboundSchema: z.ZodMiniType<
  SenderUpdateRequest$Outbound,
  SenderUpdateRequest
> = z.object({
  name: z.optional(z.string()),
  setAsDefault: z.optional(z.boolean()),
});

export function senderUpdateRequestToJSON(
  senderUpdateRequest: SenderUpdateRequest,
): string {
  return JSON.stringify(
    SenderUpdateRequest$outboundSchema.parse(senderUpdateRequest),
  );
}
