/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Capabilities = {
  /**
   * Whether SMS is enabled for this sender.
   */
  sms?: boolean | undefined;
  /**
   * Whether WhatsApp is enabled for this sender.
   */
  whatsapp?: boolean | undefined;
};

export type Sender = {
  id: string;
  name: string;
  /**
   * Phone number in E.164 format.
   */
  phoneNumber: string;
  /**
   * Whether this sender is the project's default.
   */
  isDefault?: boolean | undefined;
  capabilities?: Capabilities | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const Capabilities$inboundSchema: z.ZodMiniType<Capabilities, unknown> =
  z.object({
    sms: types.optional(types.boolean()),
    whatsapp: types.optional(types.boolean()),
  });

export function capabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<Capabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Capabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Capabilities' from JSON`,
  );
}

/** @internal */
export const Sender$inboundSchema: z.ZodMiniType<Sender, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  phoneNumber: types.string(),
  isDefault: z._default(types.boolean(), false),
  capabilities: types.optional(z.lazy(() => Capabilities$inboundSchema)),
  createdAt: types.optional(types.date()),
  updatedAt: types.optional(types.date()),
});

export function senderFromJSON(
  jsonString: string,
): SafeParseResult<Sender, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sender$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sender' from JSON`,
  );
}
