/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  WhatsAppCategory,
  WhatsAppCategory$outboundSchema,
} from "./whatsappcategory.js";

export type TemplateCreateRequest = {
  name: string;
  language?: string | undefined;
  body: string;
  /**
   * WhatsApp template category.
   */
  whatsappCategory?: WhatsAppCategory | undefined;
  variables?: Array<string> | undefined;
};

/** @internal */
export type TemplateCreateRequest$Outbound = {
  name: string;
  language: string;
  body: string;
  whatsappCategory?: string | undefined;
  variables?: Array<string> | undefined;
};

/** @internal */
export const TemplateCreateRequest$outboundSchema: z.ZodMiniType<
  TemplateCreateRequest$Outbound,
  TemplateCreateRequest
> = z.object({
  name: z.string(),
  language: z._default(z.string(), "en"),
  body: z.string(),
  whatsappCategory: z.optional(WhatsAppCategory$outboundSchema),
  variables: z.optional(z.array(z.string())),
});

export function templateCreateRequestToJSON(
  templateCreateRequest: TemplateCreateRequest,
): string {
  return JSON.stringify(
    TemplateCreateRequest$outboundSchema.parse(templateCreateRequest),
  );
}
