/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WhatsAppCategory,
  WhatsAppCategory$inboundSchema,
} from "./whatsappcategory.js";

export const Status = {
  Pending: "pending",
  Approved: "approved",
  Rejected: "rejected",
} as const;
export type Status = OpenEnum<typeof Status>;

export type Template = {
  id: string;
  /**
   * Template name (must match WhatsApp template name).
   */
  name: string;
  /**
   * Language code.
   */
  language: string;
  /**
   * Template body with variables: {{"{{"}}1}}, {{"{{"}}2}}, etc.
   */
  body: string;
  /**
   * WhatsApp template category.
   */
  category: WhatsAppCategory;
  status?: Status | undefined;
  /**
   * List of variable names for documentation.
   */
  variables?: Array<string> | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);

/** @internal */
export const Template$inboundSchema: z.ZodMiniType<Template, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
    language: types.string(),
    body: types.string(),
    category: WhatsAppCategory$inboundSchema,
    status: z._default(Status$inboundSchema, "pending"),
    variables: types.optional(z.array(types.string())),
    createdAt: types.optional(types.date()),
    updatedAt: types.optional(types.date()),
  });

export function templateFromJSON(
  jsonString: string,
): SafeParseResult<Template, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Template$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Template' from JSON`,
  );
}
