/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * WhatsApp template category.
 */
export const WhatsAppCategory = {
  Utility: "UTILITY",
  Marketing: "MARKETING",
  Authentication: "AUTHENTICATION",
} as const;
/**
 * WhatsApp template category.
 */
export type WhatsAppCategory = OpenEnum<typeof WhatsAppCategory>;

/** @internal */
export const WhatsAppCategory$inboundSchema: z.ZodMiniType<
  WhatsAppCategory,
  unknown
> = openEnums.inboundSchema(WhatsAppCategory);
/** @internal */
export const WhatsAppCategory$outboundSchema: z.ZodMiniType<
  string,
  WhatsAppCategory
> = openEnums.outboundSchema(WhatsAppCategory);
